# recipe/meta.yaml
package:
  name: pridepy
  version: "0.0.12"

source:
  path: ../

build:
  entry_points:
    - pridepy=pridepy:main
  noarch: python
  run_exports:
    - {{ pin_subpackage('pridepy', max_pin="x.x") }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vvv"
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - poetry-core >=1.2.0
  run:
    - requests~=2.31.0
    - ratelimit~=2.2.1
    - click~=8.1.7
    - pytest~=8.0.2
    - setuptools
    - boto3~=1.34.61
    - botocore~=1.34.74
    - tqdm
    - httpx

test:
  imports:
    - pridepy
  commands:
    - pridepy --help
  requires:
    - pip

about:
  home: https://www.github.com/PRIDE-Archive/pridepy
  summary: Python Client library for PRIDE Rest API
  license: MIT
  license_file: LICENSE
  dev_url: https://www.github.com/PRIDE-Archive/pridepy

extra:
  recipe-maintainers:
    - selva
