# environment.yml
name: pridepy
channels:
  - bioconda
  - conda-forge
dependencies:
  - requests>=2.32.0
  - ratelimit
  - click
  - pytest
  - setuptools
  - plotly
  - boto3
  - botocore
  - tqdm
  - urllib3
  - httpx